### ISSUE TITLE
Add an option to restore Path

### ISSUE THREAD

**Issue by YeffyCodeGit** [ANF-Studios/WinPath#38]
I think WinPath should have an option to restore the path back to its default path, in case users want to undo their changes.

**Comment by ANF-Studios** [comment]
Good suggestion!

**Comment by ANF-Studios** [comment]
Hello @YeffyCodeGit, thanks again for the suggestion. It's been added with [v0.3.0](https://github.com/ANF-Studios/WinPath/releases/tag/0.3.0). Please try it out!
