### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by ANF-Studios** [ANF-Studios/WinPath#67]
To make #65 possible, we need a plan.
I'm thinking:
* Create a `WinPath.Manager` executable.
    * It's job will be to run tasks that require administrator permissions.
    * `WinPath.Updater` shall be merged with it.
* Remove `WinPath.Updater` in favor of `WinPath.Manager`.
* Create an assembly; a dynamic library, that contains functions that are not really necessary.
    * The assembly being called `WinPath.Extensions`.
* Run tasks that do not require administrator permissions within `WinPath`.
    * Run tasks using `WinPath.Extensions`.
* Both WinPath and `WinPath.Manager` reference `WinPath.Extensions`.

**Comment by ANF-Studios** [comment]
So my question; what're your thoughts on this? And do you have a better proposal? This decision will shape WinPath.

**Comment by lylythechosenone** [comment]
Sounds good to me

**Comment by YeffyCodeGit** [comment]
good plan

**Comment by ANF-Studios** [comment]
hmm, I'm thinking.. `WinPath.Manager` could have a better name. Any suggestions?

**Comment by lylythechosenone** [comment]
`WinPath.Elevated`

**Comment by lylythechosenone** [comment]
Also get on discord, stop hiding smh

**Comment by anf** [comment]
Updater has been changed in favor of a powershell script. Extensions is probably another useless project. Not needed for now.
