### ISSUE TITLE
Add WinPath to Path on installation

### ISSUE THREAD

**Issue by YeffyCodeGit** [ANF-Studios/WinPath#8]
When the WinPath application gets installed on your computer, it should add itself to the path, as people might forget to do that themselves

**Comment by ANF-Studios** [comment]
Of course that's part of the *installation*. Else it'd literally be copying (to program files) and renaming the executable.

**Comment by ANF-Studios** [comment]
Of course that's part of the *installation*. Else it'd literally be copying (to program files) and renaming the executable.
